
package com.backup.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebService1Soap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebService1Soap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld", action = "http://tempuri.org/HelloWorld")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://tempuri.org/", className = "com.backup.webservice.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://tempuri.org/", className = "com.backup.webservice.HelloWorldResponse")
    public String helloWorld();

    /**
     * string *serverid  功能名称, string messagetext 提醒信息 , string ADDIP IP 地址, long *fileSize 文件大小, string *fileName 文件名称, string *fileType 文件类型, byte[] files 文件二进制数据
     * 
     * @param fileName
     * @param fileSize
     * @param messagetext
     * @param files
     * @param serverid
     * @param addip
     * @param fileType
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "FileServerMsg", action = "http://tempuri.org/FileServerMsg")
    @WebResult(name = "FileServerMsgResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "FileServerMsg", targetNamespace = "http://tempuri.org/", className = "com.backup.webservice.FileServerMsg")
    @ResponseWrapper(localName = "FileServerMsgResponse", targetNamespace = "http://tempuri.org/", className = "com.backup.webservice.FileServerMsgResponse")
    public String fileServerMsg(
        @WebParam(name = "serverid", targetNamespace = "http://tempuri.org/")
        String serverid,
        @WebParam(name = "messagetext", targetNamespace = "http://tempuri.org/")
        String messagetext,
        @WebParam(name = "ADDIP", targetNamespace = "http://tempuri.org/")
        String addip,
        @WebParam(name = "fileSize", targetNamespace = "http://tempuri.org/")
        long fileSize,
        @WebParam(name = "fileName", targetNamespace = "http://tempuri.org/")
        String fileName,
        @WebParam(name = "fileType", targetNamespace = "http://tempuri.org/")
        String fileType,
        @WebParam(name = "files", targetNamespace = "http://tempuri.org/")
        byte[] files);

    /**
     * string *serverid  功能名称, string messagetext 提醒信息 , string ADDIP IP 地址, string *fileName 文件名称, string *fileType 文件类型
     * 
     * @param fileName
     * @param messagetext
     * @param serverid
     * @param addip
     * @param fileType
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "FileNameServerMsg", action = "http://tempuri.org/FileNameServerMsg")
    @WebResult(name = "FileNameServerMsgResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "FileNameServerMsg", targetNamespace = "http://tempuri.org/", className = "com.backup.webservice.FileNameServerMsg")
    @ResponseWrapper(localName = "FileNameServerMsgResponse", targetNamespace = "http://tempuri.org/", className = "com.backup.webservice.FileNameServerMsgResponse")
    public String fileNameServerMsg(
        @WebParam(name = "serverid", targetNamespace = "http://tempuri.org/")
        String serverid,
        @WebParam(name = "messagetext", targetNamespace = "http://tempuri.org/")
        String messagetext,
        @WebParam(name = "ADDIP", targetNamespace = "http://tempuri.org/")
        String addip,
        @WebParam(name = "fileName", targetNamespace = "http://tempuri.org/")
        String fileName,
        @WebParam(name = "fileType", targetNamespace = "http://tempuri.org/")
        String fileType);

    /**
     * string serverid  功能名称, string messagetext 提醒信息 , string ADDIP IP地址
     * 
     * @param messagetext
     * @param serverid
     * @param addip
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "TxtServerMsg", action = "http://tempuri.org/TxtServerMsg")
    @WebResult(name = "TxtServerMsgResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TxtServerMsg", targetNamespace = "http://tempuri.org/", className = "com.backup.webservice.TxtServerMsg")
    @ResponseWrapper(localName = "TxtServerMsgResponse", targetNamespace = "http://tempuri.org/", className = "com.backup.webservice.TxtServerMsgResponse")
    public String txtServerMsg(
        @WebParam(name = "serverid", targetNamespace = "http://tempuri.org/")
        String serverid,
        @WebParam(name = "messagetext", targetNamespace = "http://tempuri.org/")
        String messagetext,
        @WebParam(name = "ADDIP", targetNamespace = "http://tempuri.org/")
        String addip);

    /**
     * Hosptail   0本院 1 南院，key  手机验证码
     * 
     * @param phoneKey
     * @param phone
     * @param hosptail
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "JumpSync", action = "http://tempuri.org/JumpSync")
    @WebResult(name = "JumpSyncResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "JumpSync", targetNamespace = "http://tempuri.org/", className = "com.backup.webservice.JumpSync")
    @ResponseWrapper(localName = "JumpSyncResponse", targetNamespace = "http://tempuri.org/", className = "com.backup.webservice.JumpSyncResponse")
    public String jumpSync(
        @WebParam(name = "Hosptail", targetNamespace = "http://tempuri.org/")
        String hosptail,
        @WebParam(name = "Phone", targetNamespace = "http://tempuri.org/")
        String phone,
        @WebParam(name = "PhoneKey", targetNamespace = "http://tempuri.org/")
        String phoneKey);

    /**
     * 
     * @param page
     * @param ipMark
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(operationName = "Restart_LogList", action = "http://tempuri.org/Restart_LogList")
    @WebResult(name = "Restart_LogListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Restart_LogList", targetNamespace = "http://tempuri.org/", className = "com.backup.webservice.RestartLogList")
    @ResponseWrapper(localName = "Restart_LogListResponse", targetNamespace = "http://tempuri.org/", className = "com.backup.webservice.RestartLogListResponse")
    public Object restartLogList(
        @WebParam(name = "page", targetNamespace = "http://tempuri.org/")
        int page,
        @WebParam(name = "ipMark", targetNamespace = "http://tempuri.org/")
        String ipMark);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(operationName = "Restart_Restart", action = "http://tempuri.org/Restart_Restart")
    @WebResult(name = "Restart_RestartResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Restart_Restart", targetNamespace = "http://tempuri.org/", className = "com.backup.webservice.RestartRestart")
    @ResponseWrapper(localName = "Restart_RestartResponse", targetNamespace = "http://tempuri.org/", className = "com.backup.webservice.RestartRestartResponse")
    public Object restartRestart(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        String id);

    /**
     * 
     * @param modularId
     * @param token
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(operationName = "Restart_RestartList", action = "http://tempuri.org/Restart_RestartList")
    @WebResult(name = "Restart_RestartListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Restart_RestartList", targetNamespace = "http://tempuri.org/", className = "com.backup.webservice.RestartRestartList")
    @ResponseWrapper(localName = "Restart_RestartListResponse", targetNamespace = "http://tempuri.org/", className = "com.backup.webservice.RestartRestartListResponse")
    public Object restartRestartList(
        @WebParam(name = "modularId", targetNamespace = "http://tempuri.org/")
        int modularId,
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token);

    /**
     * 
     * @param path
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(operationName = "Restart_FileState", action = "http://tempuri.org/Restart_FileState")
    @WebResult(name = "Restart_FileStateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Restart_FileState", targetNamespace = "http://tempuri.org/", className = "com.backup.webservice.RestartFileState")
    @ResponseWrapper(localName = "Restart_FileStateResponse", targetNamespace = "http://tempuri.org/", className = "com.backup.webservice.RestartFileStateResponse")
    public Object restartFileState(
        @WebParam(name = "path", targetNamespace = "http://tempuri.org/")
        LinkPath path);

    /**
     * Hosptail   0本院 1 南院
     * 
     * @param hospitalId
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(operationName = "DataCopy", action = "http://tempuri.org/DataCopy")
    @WebResult(name = "DataCopyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DataCopy", targetNamespace = "http://tempuri.org/", className = "com.backup.webservice.DataCopy")
    @ResponseWrapper(localName = "DataCopyResponse", targetNamespace = "http://tempuri.org/", className = "com.backup.webservice.DataCopyResponse")
    public Object dataCopy(
        @WebParam(name = "HospitalId", targetNamespace = "http://tempuri.org/")
        int hospitalId);

}
